import { useEffect, useState } from 'react';
import { 
  getCurrentUserPlaylists, 
  getPlaylistTracks, 
  createPlaylist, 
  addTracksToPlaylist, 
  getCurrentUser 
} from '../lib/spotifyAPI';
import { fetchAcousticFeaturesForTracks } from '../lib/audioFeatureEngine';
import { calculateHarmonicSequence } from '../lib/musicMath';
import Analyzer from './Analyzer';
import { Target, CheckSquare, Square, Play, Database, Sparkles, RefreshCw } from 'lucide-react';

export default function Dashboard({ onOpenLibrary }) {
  const [playlists, setPlaylists] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  
  const [targetPlaylist, setTargetPlaylist] = useState(null);
  const [masterPools, setMasterPools] = useState([]);
  const [analyzing, setAnalyzing] = useState(false);
  const [syncingPlaylistId, setSyncingPlaylistId] = useState(null);

  // Harmonic Flow sequencing state
  const [flowInProgressId, setFlowInProgressId] = useState(null);
  const [flowNotification, setFlowNotification] = useState(null);

  useEffect(() => {
    async function loadPlaylists() {
      try {
        const data = await getCurrentUserPlaylists();
        setPlaylists(data);

        // Restore saved master pool selections from localStorage
        const savedMasterIdsRaw = localStorage.getItem('spotify_saved_master_pool_ids');
        if (savedMasterIdsRaw) {
          try {
            const savedIds = JSON.parse(savedMasterIdsRaw);
            if (Array.isArray(savedIds) && savedIds.length > 0) {
              const restoredPools = data.filter(p => savedIds.includes(p.id));
              setMasterPools(restoredPools);
            }
          } catch {
            // Ignore parse errors
          }
        }
      } catch (err) {
        console.error(err);
        if (err.message?.includes('401')) {
          setError(`Your Spotify session expired! Please hit "Logout" at the top right and log back in.`);
        } else {
          setError(`Failed to fetch playlists: ${err.message}`);
        }
      } finally {
        setLoading(false);
      }
    }
    loadPlaylists();
  }, []);

  const toggleMasterPool = (playlist) => {
    let updated;
    if (masterPools.find(p => p.id === playlist.id)) {
      updated = masterPools.filter(p => p.id !== playlist.id);
    } else {
      updated = [...masterPools, playlist];
    }
    setMasterPools(updated);
    // Persist semi-permanently to localStorage
    const poolIds = updated.map(p => p.id);
    localStorage.setItem('spotify_saved_master_pool_ids', JSON.stringify(poolIds));
  };

  const handleSyncPlaylist = async (playlist, e) => {
    e.stopPropagation();
    try {
      setSyncingPlaylistId(playlist.id);
      setFlowNotification({ type: 'info', message: `Refreshing "${playlist.name}" from Spotify...` });
      await getPlaylistTracks(playlist.id, true); // forceRefresh=true
      setFlowNotification({ type: 'success', message: `✓ "${playlist.name}" refreshed and cached in IndexedDB!` });
    } catch (err) {
      console.error(err);
      setFlowNotification({ type: 'error', message: `Sync failed: ${err.message}` });
    } finally {
      setSyncingPlaylistId(null);
    }
  };

  const handleCreateHarmonicFlowCopy = async (playlist, e) => {
    e.stopPropagation();
    try {
      setFlowInProgressId(playlist.id);
      setFlowNotification({ type: 'info', message: `Analyzing & sequencing "${playlist.name}"...` });

      const raw = await getPlaylistTracks(playlist.id);
      const tracks = raw.filter(t => (t.item || t.track) && !t.is_local).map(t => t.item || t.track);

      if (tracks.length === 0) {
        throw new Error("Playlist has no valid tracks.");
      }

      const { tracksWithFeatures } = await fetchAcousticFeaturesForTracks(tracks);
      const sequencedTracks = calculateHarmonicSequence(tracksWithFeatures);
      const uris = sequencedTracks.map(t => t.uri);

      const user = await getCurrentUser();
      const newPlaylist = await createPlaylist(
        user.id,
        `${playlist.name} - Harmonic Flow`,
        `Smooth Camelot key & energy transition copy generated by Spotify Sorter.`
      );

      for (let i = 0; i < uris.length; i += 100) {
        await addTracksToPlaylist(newPlaylist.id, uris.slice(i, i + 100));
      }

      setFlowNotification({
        type: 'success',
        message: `Created "${playlist.name} - Harmonic Flow" on Spotify with ${sequencedTracks.length} smoothly ordered tracks!`
      });

      // Reload playlist list
      const refreshedPlaylists = await getCurrentUserPlaylists();
      setPlaylists(refreshedPlaylists);

    } catch (err) {
      console.error(err);
      setFlowNotification({ type: 'error', message: `Flow error: ${err.message}` });
    } finally {
      setFlowInProgressId(null);
    }
  };

  if (analyzing && targetPlaylist) {
    return <Analyzer targetPlaylist={targetPlaylist} masterPools={masterPools} onBack={() => setAnalyzing(false)} />;
  }

  if (loading) {
    return (
      <div className="glass-panel" style={{ textAlign: 'center', padding: '3rem' }}>
        <h3>Loading your playlists from Spotify...</h3>
      </div>
    );
  }

  if (error) {
    return <div className="glass-panel"><p style={{ color: 'var(--accent-red)' }}>{error}</p></div>;
  }

  return (
    <div className="animate-fade-in">
      {/* Top Banner */}
      <div className="glass-panel" style={{ marginBottom: '1.5rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '1.5rem' }}>
        <div>
          <h2 style={{ fontSize: '1.6rem', marginBottom: '0.5rem' }}>Setup Playlist Analysis</h2>
          <p style={{ color: 'var(--text-secondary)', margin: 0, fontSize: '0.95rem' }}>
            1. Select one <strong>Target Playlist</strong> to clean up outliers.<br/>
            2. (Optional) Select one or more <strong>Master Pools</strong> to pull harmonic vibe suggestions from.
          </p>
        </div>

        <div style={{ display: 'flex', gap: '0.75rem', alignItems: 'center' }}>
          {onOpenLibrary && (
            <button 
              className="btn-secondary" 
              onClick={onOpenLibrary}
              style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', borderColor: 'rgba(0, 212, 255, 0.4)' }}
            >
              <Database size={16} color="#00d4ff" />
              Acoustic Library
            </button>
          )}

          <button 
            className="btn-primary" 
            onClick={() => setAnalyzing(true)}
            disabled={!targetPlaylist}
            style={{ 
              opacity: targetPlaylist ? 1 : 0.5, 
              cursor: targetPlaylist ? 'pointer' : 'not-allowed',
              padding: '0.75rem 1.6rem'
            }}
          >
            <Play size={18} />
            Start Analysis
          </button>
        </div>
      </div>

      {/* Harmonic Flow Alert Notification */}
      {flowNotification && (
        <div style={{
          padding: '0.75rem 1.2rem',
          borderRadius: '10px',
          marginBottom: '1.5rem',
          backgroundColor: flowNotification.type === 'success' ? 'rgba(29, 185, 84, 0.15)' : flowNotification.type === 'error' ? 'rgba(231, 76, 60, 0.15)' : 'rgba(0, 212, 255, 0.15)',
          border: `1px solid ${flowNotification.type === 'success' ? 'var(--accent-green)' : flowNotification.type === 'error' ? 'var(--accent-red)' : '#00d4ff'}`,
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          fontSize: '0.9rem'
        }}>
          <span>{flowNotification.message}</span>
          <button onClick={() => setFlowNotification(null)} style={{ background: 'none', border: 'none', color: '#fff', cursor: 'pointer', fontSize: '0.8rem' }}>Dismiss</button>
        </div>
      )}
      
      {/* Playlists Grid */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))', gap: '1.5rem' }}>
        {playlists.map(p => p && (
          <div key={p.id || Math.random()} className="glass-panel" style={{ 
            padding: '1rem', 
            transition: 'all 0.2s',
            border: targetPlaylist?.id === p?.id ? '2px solid var(--accent-green)' : masterPools.find(pool => pool?.id === p?.id) ? '2px solid var(--accent-purple)' : '1px solid var(--glass-border)',
            display: 'flex',
            flexDirection: 'column'
          }}>
            {p?.images && p.images.length > 0 && p.images[0] ? (
              <img src={p.images[0].url} alt={p?.name || 'Playlist'} style={{ width: '100%', aspectRatio: '1', objectFit: 'cover', borderRadius: '8px', marginBottom: '0.75rem' }} />
            ) : (
              <div style={{ width: '100%', aspectRatio: '1', backgroundColor: 'rgba(255,255,255,0.06)', borderRadius: '8px', marginBottom: '0.75rem', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--text-secondary)' }}>
                No Cover Art
              </div>
            )}
            
            <h4 style={{ margin: '0 0 0.25rem 0', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }} title={p?.name}>{p?.name || 'Unnamed Playlist'}</h4>
            <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', marginBottom: '0.75rem' }}>{p?.items?.total || p?.tracks?.total || 0} tracks</p>
            
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.45rem', marginTop: 'auto' }}>
              <button 
                className="btn-secondary" 
                style={{ 
                  display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.4rem',
                  backgroundColor: targetPlaylist?.id === p?.id ? 'var(--accent-green)' : 'transparent',
                  color: targetPlaylist?.id === p?.id ? '#000' : '#fff',
                  borderColor: targetPlaylist?.id === p?.id ? 'var(--accent-green)' : 'rgba(255,255,255,0.2)',
                  fontWeight: targetPlaylist?.id === p?.id ? 'bold' : 'normal',
                  fontSize: '0.8rem',
                  padding: '0.4rem'
                }}
                onClick={() => setTargetPlaylist(p?.id === targetPlaylist?.id ? null : p)}
              >
                <Target size={15} />
                {targetPlaylist?.id === p?.id ? 'Target Selected' : 'Set as Target'}
              </button>
              
              <button 
                className="btn-secondary" 
                style={{ 
                  display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.4rem',
                  backgroundColor: masterPools.find(pool => pool?.id === p?.id) ? 'rgba(138, 43, 226, 0.3)' : 'transparent',
                  borderColor: masterPools.find(pool => pool?.id === p?.id) ? 'var(--accent-purple)' : 'rgba(255,255,255,0.2)',
                  fontSize: '0.8rem',
                  padding: '0.4rem'
                }}
                onClick={() => toggleMasterPool(p)}
                title="Toggle Master Pool (automatically saved for future sessions)"
              >
                {masterPools.find(pool => pool?.id === p?.id) ? <CheckSquare size={15} color="var(--accent-purple)" /> : <Square size={15} />}
                {masterPools.find(pool => pool?.id === p?.id) ? '📌 Master (Saved)' : 'Master Pool'}
              </button>

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.3rem', marginTop: '0.2rem' }}>
                {/* Re-Sync Button */}
                <button
                  className="btn-secondary"
                  disabled={syncingPlaylistId === p.id}
                  onClick={(e) => handleSyncPlaylist(p, e)}
                  style={{
                    display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.25rem',
                    fontSize: '0.7rem',
                    padding: '0.3rem 0.2rem',
                    borderColor: 'rgba(255, 255, 255, 0.15)',
                    color: 'var(--text-secondary)'
                  }}
                  title="Re-download playlist tracks from Spotify into IndexedDB"
                >
                  <RefreshCw size={11} className={syncingPlaylistId === p.id ? "animate-spin" : ""} />
                  {syncingPlaylistId === p.id ? 'Syncing...' : 'Re-Sync'}
                </button>

                {/* Optional Harmonic Flow Copy Button */}
                <button
                  className="btn-secondary"
                  disabled={flowInProgressId === p.id}
                  onClick={(e) => handleCreateHarmonicFlowCopy(p, e)}
                  style={{
                    display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.25rem',
                    fontSize: '0.7rem',
                    padding: '0.3rem 0.2rem',
                    borderColor: 'rgba(0, 212, 255, 0.3)',
                    color: '#00d4ff',
                    backgroundColor: 'rgba(0, 212, 255, 0.05)'
                  }}
                  title="Create a separate, smoothly sequenced copy based on Camelot wheel & tempo progression"
                >
                  {flowInProgressId === p.id ? (
                    <RefreshCw size={11} className="animate-spin" />
                  ) : (
                    <Sparkles size={11} color="#00d4ff" />
                  )}
                  {flowInProgressId === p.id ? '...' : 'Flow Copy'}
                </button>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
